source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'haml-rails'
gem 'therubyracer'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier'
end

group :production do
  gem 'pg'
end

group :development do
  gem 'sqlite3'
end

gem 'jquery-rails'
gem 'sass-rails', '~> 3.2.3'
gem 'compass-rails'
